### PR TITLE
Feature/google maps

### PR DESCRIPTION
**Pull request by briane92**

### CODE REVIEW

**Comment by briane92** [comment]
The Google Map constantly reloads , especially after resizing the window

**Comment by gruenberger** [comment]
did u read the docs?!
https://www.npmjs.com/package/@googlemaps/react-wrapper

**Comment by briane92** [comment]
yes I read the fucking docs. The docs aren't even up to date for type script.

**Comment by briane92** [comment]
I'm going try pulling the state up and pass it to the map component

**Comment by gruenberger** [comment]
If all else fails-- https://www.npmjs.com/package/@react-google-maps/api

**Comment by briane92** [comment]
> If all else fails-- https://www.npmjs.com/package/@react-google-maps/api

Not made by google, there's already a lot of layers using next js on top of react. But I will switch over if you absolutely want me too.

**Comment by briane92** [comment]
This is good to go now. I think

**Review by gruenberger — APPROVED** [review]

**Pull request merged**
